name: Publish NuGet Packages

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Directory.Build.props'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Pack Core (only for local reference)
        run: dotnet pack src/GenerateEverything.Core/GenerateEverything.Core.csproj -c Release -o ./local-packages

      - name: Add local package source
        run: dotnet nuget add source ./local-packages --name local-temp

      - name: Restore Generator (with local Core)
        run: dotnet restore src/GenerateEverything.Generator/GenerateEverything.Generator.csproj --source ./local-packages --source https://api.nuget.org/v3/index.json

      - name: Pack Generator
        run: dotnet pack src/GenerateEverything.Generator/GenerateEverything.Generator.csproj -c Release -o ./nupkg

      - name: Push Generator to NuGet
        run: dotnet nuget push ./nupkg/GenerateEverything.Generator.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
